on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container:
      image: centos:7
      options: -v /__w/test-centos7-ri-build/test-centos7-ri-build/cmakebuild/packages:/packages/:rw
    steps:

    - name: Build ResInsight
      run: |
        mkdir cmakebuild
        cd cmakebuild
        mkdir packages
        cd packages
        echo "something" > test.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ResInsight
        path: /packages
