on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
    - name: Intall Dependencies
      run: | 
        yum install -y centos-release-scl
        yum-config-manager --enable rhel-server-rhscl-7-rpms

        yum install -y qt5-qtbase
        yum install -y qt5-qtbase-devel
        yum install -y qt5-qtscript-devel

        yum install -y cmake
        yum install -y git
        yum install -y make

        yum install -y mesa-libGL-devel
        yum install -y freeglut-devel

        yum install -y devtoolset-6

    - name: Build ResInsight
      run: | 
        cmake --version
        git --version
              
        source /opt/rh/devtoolset-6/enable

        git clone git://github.com/OPM/ResInsight.git ResInsight
        mkdir cmakebuild
        cd cmakebuild
        cmake ../ResInsight
        make -j8
        make package

      - name: Upload artifact
          uses: actions/upload-artifact@v1
          with:
            name: ResInsight
            path: ${{ runner.workspace }}/ResInsight/cmakebuild/packages
