on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container: centos:7
      volumes:
        - $GITHUB_WORKSPACE/package:/shared_package
    steps:

    - name: Build ResInsight
      run: echo "something" > /shared_package/test.txt


    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ResInsight
        path: ${{ runner.workspace }}/package
