on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
    - name: Intall Zip
      run: | 
        yum install -y centos-release-scl
        yum-config-manager --enable rhel-server-rhscl-7-rpms

        yum install -y qt5-qtbase
        yum install -y qt5-qtbase-devel
        yum install -y qt5-qtscript-devel

        yum install -y cmake
        yum install -y git
        yum install -y make

        yum install -y mesa-libGL-devel
        yum install -y freeglut-devel

        yum install -y devtoolset-6
        source /opt/rh/devtoolset-6/enable

        cmake --version
        git --version
              