on: [push]

jobs:
  build_on_centos7:
    runs-on: ubuntu-latest
    container:
      image: centos:7
      options: -v /__w/test-centos7-ri-build/test-centos7-ri-build/cmakebuild/packages:/packages:rw
    steps:
    - name: Intall Dependencies
      run: | 
        yum install -y centos-release-scl
        yum-config-manager --enable rhel-server-rhscl-7-rpms
      
        yum install -y https://repo.ius.io/ius-release-el7.rpm
        yum install -y git222

        yum install -y qt5-qtbase
        yum install -y qt5-qtbase-devel
        yum install -y qt5-qtscript-devel

        yum install -y cmake3
        yum install -y make

        yum install -y mesa-libGL-devel
        yum install -y freeglut-devel

        yum install -y devtoolset-7
        
        yum install -y rh-python36
     
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install grpcio-tools

    - name: Build ResInsight
      run: | 
        cmake --version
        git --version
              
        source /opt/rh/devtoolset-7/enable

        git clone git://github.com/OPM/ResInsight.git ResInsight
        cd ResInsight
        git submodule update --init
        
        cd vcpkg
        ./bootstrap-vcpkg.sh 
        ./vcpkg install grpc
        
        mkdir cmakebuild
        cd cmakebuild
        cmake3 \
        -DRESINSIGHT_QT5_BUNDLE_LIBRARIES=ON \
        -DRESINSIGHT_ENABLE_GRPC=true \
        -DVCPKG_TARGET_TRIPLET=x64-linux \
        -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake \
        -DRESINSIGHT_GRPC_PYTHON_EXECUTABLE=python3 \
        ../ResInsight
        
        make -j8
        make package
        rm -rf packages/_CPack_Packages

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ResInsight
        path: ./cmakebuild/packages
