on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
    - name: Intall Zip
      run: | 
        apt-get update
        apt-get install zip -y      
      